service: apollo-lambda
provider:
  name: aws
  runtime: nodejs8.10
  # memorySize: 512 # optional, in MB, default is 1024
  timeout: 20 # optional, in seconds, default is 6
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
